import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Gallery from "@/components/Gallery";
import { getPage } from "@/lib/apod";

// Static export: only the routes generated by generateStaticParams exist at runtime.
// Any out-of-bounds page (e.g. /page/999) returns 404 instead of attempting on-demand SSR.
export const dynamicParams = false;

// Generates the static routes to prerender at build time.
// Page 1 is already handled by the root page.tsx ("/"), so here we generate /page/2 through /page/12.
export async function generateStaticParams() {
  const first = await getPage(1);
  if (!first) return [];

  // Generate string params: [{ page: "2" }, { page: "3" }, ...]
  return Array.from({ length: first.totalPages - 1 }, (_, i) => ({ page: String(i + 2) }));
}

// Next.js 15+: params is an async Promise that must be awaited
export async function generateMetadata({ params }: PageProps<"/page/[page]">): Promise<Metadata> {
  return { title: `Page ${(await params).page} | APOD Explorer` };
}

export default async function ArchivePage({ params }: PageProps<"/page/[page]">) {
  const { page } = await params;
  const result = await getPage(Number(page));
  if (!result) notFound();

  return <Gallery {...result} />;
}
